# Generated by Django 2.2.4 on 2019-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, 'Beginner'), (2, 'Advanced'), (3, 'Expert')], default=1, max_length=1)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sporttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Sporttype',
                'verbose_name_plural': 'Sporttypes',
                'ordering': ['-id'],
            },
        ),
    ]
