# Generated by Django 2.2.4 on 2019-12-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='level',
        ),
    ]
