# Generated by Django 2.2.4 on 2019-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_sport_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='level',
            field=models.CharField(choices=[(1, 'Beginner'), (2, 'Advanced'), (3, 'Expert')], default=1, max_length=1),
        ),
    ]
