# Generated by Django 2.2.4 on 2019-12-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191118_2057'),
        ('sports', '0003_sport_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='sporttype',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='sports.Sporttype'),
            preserve_default=False,
        ),
    ]
