# Generated by Django 2.2.4 on 2019-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_auto_20191215_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
