# Generated by Django 2.2.4 on 2019-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20191215_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Advanced'), (3, 'Expert')], default=1, max_length=1),
        ),
    ]
