# Generated by Django 2.2.4 on 2019-12-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_auto_20191215_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Advanced'), (3, 'Expert')], default=1),
        ),
        migrations.AlterField(
            model_name='sport',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='profiles.Profile'),
        ),
    ]
