# Generated by Django 2.2.4 on 2019-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_auto_20191215_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='sporttype',
        ),
        migrations.AddField(
            model_name='sport',
            name='sporttype',
            field=models.ManyToManyField(to='sports.Sporttype'),
        ),
    ]
