# Generated by Django 2.2.4 on 2019-12-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_auto_20191215_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='sporttype',
        ),
        migrations.AddField(
            model_name='sport',
            name='sporttype',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sports.Sporttype'),
            preserve_default=False,
        ),
    ]
