# Generated by Django 2.2.8 on 2020-02-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_auto_20191215_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='profile',
        ),
    ]
