# Generated by Django 2.2.8 on 2020-02-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_remove_sport_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='profile',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='sports.Sport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sport',
            name='sporttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sporttype', to='sports.Sporttype'),
        ),
    ]
