# Generated by Django 2.2.8 on 2020-03-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_auto_20200204_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['-level', '-sporttype'], 'verbose_name': 'Sport', 'verbose_name_plural': 'Sports'},
        ),
        migrations.AlterModelOptions(
            name='sporttype',
            options={'ordering': ['-title'], 'verbose_name': 'Sporttype', 'verbose_name_plural': 'Sporttypes'},
        ),
    ]
