# Generated by Django 2.2.4 on 2019-12-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_profile',
            new_name='profile',
        ),
    ]
