# Generated by Django 2.2.4 on 2019-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191118_2057'),
        ('reviews', '0003_auto_20191220_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ManyToManyField(related_name='review_profile', to='profiles.Profile'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_author',
        ),
        migrations.AddField(
            model_name='review',
            name='review_author',
            field=models.ManyToManyField(related_name='review_author', to='profiles.Profile'),
        ),
    ]
