# Generated by Django 2.2.4 on 2019-12-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20191220_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_author',
            new_name='author',
        ),
    ]
