# Generated by Django 2.2.4 on 2019-12-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20191220_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
