# Generated by Django 2.2.4 on 2019-12-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
