# Generated by Django 2.2.4 on 2019-12-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20191226_1624'),
        ('reviews', '0010_auto_20191220_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('is_published', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='profiles.Profile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Review')),
            ],
            options={
                'verbose_name': 'Review Response',
                'verbose_name_plural': 'Review Reponses',
                'ordering': ['-created_date'],
            },
        ),
    ]
