# Generated by Django 2.2.8 on 2020-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_reviewresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='review_response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_response', to='reviews.ReviewResponse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_response_author', to='profiles.Profile'),
        ),
    ]
