# Generated by Django 2.2.8 on 2020-02-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_auto_20200204_1426'),
        ('reviews', '0012_auto_20200204_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_response',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='sports.Sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Review'),
            preserve_default=False,
        ),
    ]
