# Generated by Django 2.2.8 on 2020-04-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20200328_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'ordering': ['-created_date'], 'verbose_name': 'Review Response', 'verbose_name_plural': 'Review Responses'},
        ),
    ]
