# Generated by Django 2.2.4 on 2019-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191118_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_rating',
            field=models.IntegerField(null=True),
        ),
    ]
