# Generated by Django 2.2.4 on 2019-12-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
