# Generated by Django 2.2.4 on 2019-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20191220_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
