# Generated by Django 2.2.8 on 2020-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20200204_1256'),
        ('profiles', '0011_auto_20200113_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Review'),
            preserve_default=False,
        ),
    ]
