# Generated by Django 2.2.8 on 2020-02-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_remove_sport_profile'),
        ('profiles', '0012_profile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='sports.Sport'),
            preserve_default=False,
        ),
    ]
