# Generated by Django 2.2.8 on 2020-02-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='sports.Sport'),
        ),
    ]
