# Generated by Django 2.2.8 on 2020-04-02 11:56

from django.db import migrations, models
import main.management.validators.filevalidator
import main.management.validators.pathandname


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_auto_20200402_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.FileField(blank=True, default='', upload_to=main.management.validators.pathandname.PathAndRename(sub_path='certificates'), validators=[main.management.validators.filevalidator.FileValidator(content_types=('image/jpeg', 'image/jpg'), max_size=2048000)]),
        ),
    ]
