# Generated by Django 2.2.8 on 2020-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_auto_20200402_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
